export const playlistMatrix = [
    [
        "Heatblast",
        "Four Arms",
        "XLR8",
        "Diamondhead",
        "Upgrade",
        "Ghostfreak",
        "Stinkfly",
        "Grey Matter",
        "Wildmutt",
        "Ripjaws",
    ],
    [
        "Cannonbolt",
        "Wildvine",
        "Blitzwolfer",
        "Snare-oh",
        "Frankenstrike",
        "Upchuck",
        "Ditto",
        "Eye Guy",
        "Way Big",
        "Arctiguana",
    ],
    [
        "Swampfire",
        "Echo Echo",
        "Humungousaur",
        "Jetray",
        "Big Chill",
        "Chromastone",
        "Brainstorm",
        "Spidermonkey",
        "Goop",
        "Alien X",
    ],
    [
        "Lodestar",
        "Rath",
        "Nanomech",
        "Murk Upchuck",
        "Water Hazard",
        "Terraspin",
        "NRG",
        "Armodrillo",
        "AmpFibian",
        "Fasttrack",
    ],
    [
        "Jury Rigg",
        "Gravattack",
        "Shocksquatch",
        "Eatle",
        "Clockwork",
        "Buzzshock",
        "ChamAlien",
        "Astrodactyl",
        "Crashhopper",
        "Toepick",
    ],
    [
        "Toepick",
        "Bloxx",
        "Feedback",
        "Ball Weevil",
        "Walkatrout",
        "Pesky Dust",
        "Mole-Stache",
        "The Worst",
        "Atomix",
        "Whampire",
    ],
]
